- name: import nodesource ppa
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
    validate_certs: no

- name: add node source repo
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
    update_cache: yes
    state: present

- name: install nodejs
  apt: pkg=nodejs state=latest
