- name: check if the unicorn gem is installed
  stat: path=/usr/local/bin/unicorn
  register: unicorn_bin

- name: install unicorn
  command: "{{ item }}"
  with_items:
    - gem install unicorn --no-document
  when: not unicorn_bin.stat.exists

- name: deploy unicorn config
  template:
    src: unicorn.conf.rb
    dest: /home/sinatra/current/unicorn.conf.rb
    owner: sinatra
    group: sinatra
    mode: 0664

- include_tasks: systemd.yml
