- name: copy sinatra systemd service
  template:
    src: systemd/sinatra.service
    dest: /lib/systemd/system/sinatra.service
    owner: root
    group: root
    mode: 0644

- name: is unicorn running
  command: cat /home/sinatra/shared/pids/unicorn.pid
  register: old_unicorn
  ignore_errors: true

- name: hot restart unicorn
  command: kill -s USR2 "{{ old_unicorn.stdout }}"
  when: old_unicorn is succeeded

- name: start unicorns via systemd
  systemd: name=sinatra.service state=started enabled=yes
  when: old_unicorn is failed
