- include_tasks: system.yml

- include_tasks: user.yml

- name: create env var export script from template
  template:
    src: environment.sh
    dest: /etc/profile.d/rails.sh
    mode: 0644
    owner: root
    group: root

- name: set kyrylo.org directory permissions
  file:
    path: /home/rails/shared/{{ item }}
    state: directory
    recurse: yes
    owner: rails
    group: rails
    mode: 0777
  with_items:
    - assets
    - config
    - log
    - pids
    - public
    - sockets

- name: set cached_copy permissions
  file:
    path: /home/rails/shared/cached_copy
    owner: rails
    group: rails
    mode: 0777
    recurse: true
    state: directory

- name: set release
  command: /bin/date +"%Y%m%d%H%M%S"
  register: date

- name: checkout kyrylo.org code
  git:
    repo: ssh://git@github.com/kyrylo/kyrylo.org.git
    dest: /home/rails/shared/cached_copy/
    version: production
    accept_hostkey: true
    update: yes
    force: yes
    key_file: /home/rails/.ssh/deploy_key

- name: export copy of code to release
  command: git checkout-index -f -a --prefix="/var/tmp/{{ date.stdout }}/"
  args:
    chdir: /home/rails/shared/cached_copy

- name: create database.yml
  template:
    src: database.yml
    dest: /home/rails/shared/config/
    owner: rails
    group: rails
    mode: 0664

- name: create imgur.yml
  template:
    src: imgur.yml
    dest: /home/rails/shared/config/
    owner: rails
    group: rails
    mode: 0664

- name: link database config
  file:
    src: /home/rails/shared/config/database.yml
    dest: /var/tmp/{{ date.stdout }}/config/database.yml
    owner: rails
    group: rails
    mode: 0644
    state: link
    force: true

- name: link imgur config
  file:
    src: /home/rails/shared/config/imgur.yml
    dest: /var/tmp/{{ date.stdout }}/config/imgur.yml
    owner: rails
    group: rails
    mode: 0644
    state: link
    force: true

- name: delete git tracked log dir
  file: path=/var/tmp/{{ date.stdout }}/log state=absent

- name: link shared log directory
  file:
    src: /home/rails/shared/log
    dest: /var/tmp/{{ date.stdout }}/log
    state: link
    owner: rails
    group: rails
    mode: 0775

- name: change ownership of release
  file:
    path: "{{ item }}"
    owner: rails
    group: rails
    recurse: yes
    state: directory
  with_items:
    - /var/tmp/{{ date.stdout }}
    - /home/rails/shared

- name: deploy current release
  file:
    src: /var/tmp/{{ date.stdout }}
    dest: /home/rails/current
    state: link
    owner: rails
    group: rails
    mode: 0755

- include_tasks: config.yml
